### PR TITLE
Update to 2.29

### PR DESCRIPTION
**Pull request by WardBrian**
- Removed C++ specific reserved words
- Updated functions
- Added 'array' as a valid type keyword.

### CODE REVIEW

**Comment by WardBrian** [comment]
@kaz-yos are you able to quickly review this? My hope is to update this, then atom-language-stan so we can get better highlighting on GitHub

**Comment by kaz-yos** [comment]
Looks good to me. Thanks!

**Comment by WardBrian** [comment]
Thanks @kaz-yos - do you also have write access in https://github.com/jrnold/atom-language-stan/ ?

**Comment by kaz-yos** [comment]
I do not have write access to that one.

**Pull request merged**
